---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: docker.io/jcabrero/flask-grayscale:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: minio_secret_key
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: minio_secret_key
            - name: minio_access_key
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: minio_access_key
            - name: minio_input_bucket
              value: initial
            - name: minio_output_bucket
              value: grayscale
            - name: minio_endpoint
              value: 10.0.0.2:9000 # Needed otherwise CoreDNS will not redirect to MINIO.

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer
