---
apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
type: Opaque
data:
  #minio_access_key: `echo -n "accesskey" | base64`
  minio_access_key: YWNjZXNza2V5
  #minio_secret_key: `echo -n "secretkey" | base64`
  minio_secret_key: c2VjcmV0a2V5