---
apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
type: Opaque
data:
  #minio_access_key: 1JZ0vglLbyTlvmvQu82s
  minio_access_key: MUpaMHZnbExieVRsdm12UXU4MnM=
  #minio_secret_key: ZcwKlRvBWp4aRhmpdQTh0qGJHruSQhbDeoiuXogT
  minio_secret_key: WmN3S2xSdkJXcDRhUmhtcGRRVGgwcUdKSHJ1U1FoYkRlb2l1WG9nVA==